"""Add audio_url to Story

Revision ID: e80637ab55dd
Revises: 005_languages
Create Date: 2026-05-01 04:09:32.451653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e80637ab55dd'
down_revision: Union[str, None] = '005_languages'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_decks_is_public', table_name='decks')
    op.drop_constraint('uq_languages_code', 'languages', type_='unique')
    op.drop_index('ix_languages_code', table_name='languages')
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=True)
    op.add_column('stories', sa.Column('audio_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'audio_url')
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.create_index('ix_languages_code', 'languages', ['code'], unique=False)
    op.create_unique_constraint('uq_languages_code', 'languages', ['code'])
    op.create_index('ix_decks_is_public', 'decks', ['is_public'], unique=False)
    # ### end Alembic commands ###
